# Generated by Django 2.2.2 on 2019-06-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReminderApp', '0003_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='meaaseg',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
