# Generated by Django 2.2.2 on 2019-06-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReminderApp', '0004_auto_20190605_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='task_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
